name: Flutter Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Cache Flutter and Dependencies
        uses: actions/cache@v3
        with:
          paths: |
            $HOME/.pub-cache/
            $HOME/flutter/bin/cache/
            ./android/.gradle/
          key: ${{ runner.os }}-flutter-${{ hashFiles('pubspec.yaml') }}

      - name: Check Flutter Installation
        run: |
          flutter --version
          if [ $? -eq 0 ]; then
            echo "Flutter is installed!"
          else
            echo "Flutter is not installed! Please check runner configuration."
            exit 1
          fi

      - name: Install Dependencies
        run: flutter pub get

      - name: Create Native Splash Screen
        run: flutter pub run flutter_native_splash:create

      - name: Create Keystore (using Secrets)
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > ./android/app/my-release-key.jks

      - name: Validate Keystore (using Secrets)
        run: |
          keytool -v -list -keystore ./android/app/my-release-key.jks -storepass ${{ secrets.KEYSTORE_PASSWORD }}

      - name: Build App Bundle (using Secrets)
        run: |
          cd android
          ./gradlew assembleRelease -Pandroid.injected.signing.store.file=./app/my-release-key.jks \
            -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} \
            -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} \
            -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}

      - name: Validate AAB
        run: |
          apksigner verify --verbose android/app/build/outputs/bundle/release/app-release.aab

      - name: Upload AAB
        uses: actions/upload-artifact@v3
        with:
          name: flutter_app_aab
          path: android/app/build/outputs/bundle/release/app-release.aab
          retention-days: 30
